module github.com/martianoff/gala_demo_pkg_import_bazel

go 1.21

// GALA-managed Go dependencies below. DO NOT EDIT.
// Code generated by gala mod tidy. DO NOT EDIT.
require (
	github.com/google/uuid v1.6.0 // indirect
)
// End GALA-managed dependencies.
